unit UDM;

interface

uses
  SysUtils, Classes, DBXpress, DB, SqlExpr, IdBaseComponent, IdComponent,
  IdTCPConnection, IdTCPClient, IdAntiFreezeBase, IdAntiFreeze, Messages,
  Dialogs, FMTBcd, DBClient, Provider;

type
  TDM = class(TDataModule)
    SQLConnectionLocal: TSQLConnection;
    SQLConnectionRetaguarda: TSQLConnection;
    TCPTestaConexao: TIdTCPClient;
    IdAntiFreeze: TIdAntiFreeze;
    SQLStoredProcClientes: TSQLStoredProc;
    SQLStoredProcEstoque: TSQLStoredProc;
    QVerificaCadClientes: TSQLQuery;
    QVerificaCadClientesCODIGO: TIntegerField;
    QVerificaCadClientesNOME: TStringField;
    QVerificaCadClientesENDERECO: TStringField;
    QVerificaCadClientesBAIRRO: TStringField;
    QVerificaCadClientesCIDADE: TStringField;
    QVerificaCadClientesUF: TStringField;
    QVerificaCadClientesCEP: TStringField;
    QVerificaCadClientesTELEFONE: TStringField;
    QVerificaCadClientesCELULAR: TStringField;
    QVerificaCadClientesCPF: TStringField;
    QVerificaCadClientesRG: TStringField;
    QVerificaCadClientesCGC: TStringField;
    QVerificaCadClientesIE: TStringField;
    QVerificaCadClientesINADIMPLENTE: TStringField;
    QVerificaCadClientesTRAVA: TFMTBCDField;
    QVerificaCadClientesLIMITECREDITO: TFMTBCDField;
    QVerificaCadClientesOBS: TBlobField;
    QVerificaCadClientesCODCIDADE: TIntegerField;
    QVerificaCadClientesCODBAIRRO: TIntegerField;
    QVerificaCadClientesINATIVO: TStringField;
    QVerificaCadClientesULT_ALTERACAO: TSQLTimeStampField;
    TDeploy: TClientDataSet;
    TDeployID: TAutoIncField;
    QPegaDataHora: TSQLQuery;
    QPegaDataHoraCURRENT_TIMESTAMP: TSQLTimeStampField;
    QVerificaCadEstoque: TSQLQuery;
    QVerificaCadEstoqueCODIGO: TIntegerField;
    QVerificaCadEstoqueCODBARRA: TStringField;
    QVerificaCadEstoqueREFERENCIA: TStringField;
    QVerificaCadEstoqueDESCRICAO: TStringField;
    QVerificaCadEstoqueCODGRUPO: TIntegerField;
    QVerificaCadEstoqueCODMARCA: TIntegerField;
    QVerificaCadEstoqueQTDE: TFMTBCDField;
    QVerificaCadEstoqueQTDEEF: TFMTBCDField;
    QVerificaCadEstoqueQTDEMINIMA: TFMTBCDField;
    QVerificaCadEstoqueCUSTOFINAL: TFMTBCDField;
    QVerificaCadEstoquePRECOVENDA: TFMTBCDField;
    QVerificaCadEstoquePRECOPRAZO: TFMTBCDField;
    QVerificaCadEstoqueDESCONTOMAX: TFMTBCDField;
    QVerificaCadEstoqueMED: TStringField;
    QVerificaCadEstoqueCODALIQUOTA: TIntegerField;
    QVerificaCadEstoqueBALANCA: TStringField;
    QVerificaCadEstoqueCODSECAO: TIntegerField;
    QVerificaCadEstoqueOBS: TBlobField;
    QVerificaCadEstoqueIPI: TFMTBCDField;
    QVerificaCadEstoqueCOD_ST: TSmallintField;
    QVerificaCadEstoqueINATIVO: TStringField;
    QVerificaCadEstoqueULT_ALTERACAO: TSQLTimeStampField;
    TDeployULT_RECEBIDOS: TDateTimeField;
    TDeployULT_ENVIADOS: TDateTimeField;
    QVerificaCadEmpresa: TSQLQuery;
    QVerificaCadEmpresaCODIGO: TIntegerField;
    QVerificaCadEmpresaRAZAO: TStringField;
    QVerificaCadEmpresaNOME: TStringField;
    QVerificaCadEmpresaENDERECO: TStringField;
    QVerificaCadEmpresaBAIRRO: TStringField;
    QVerificaCadEmpresaCOD_CIDADE: TIntegerField;
    QVerificaCadEmpresaUF: TStringField;
    QVerificaCadEmpresaCEP: TStringField;
    QVerificaCadEmpresaCGC: TStringField;
    QVerificaCadEmpresaIE: TStringField;
    QVerificaCadEmpresaFONE: TStringField;
    QVerificaCadEmpresaFAX: TStringField;
    QVerificaCadEmpresaULT_ALTERACAO: TSQLTimeStampField;
    QVerificaCadEmpresaNOME_CIDADE: TStringField;
    SQLStoredProcEmpresas: TSQLStoredProc;
    QGen: TSQLQuery;
    SQLStoredProcMarca: TSQLStoredProc;
    SQLStoredProcGrupo: TSQLStoredProc;
    SQLStoredProcSecao: TSQLStoredProc;
    QVerificaCadMarca: TSQLQuery;
    QVerificaCadGrupo: TSQLQuery;
    QVerificaCadSecao: TSQLQuery;
    SQLStoredProcEcfAliquota: TSQLStoredProc;
    QVerificaCadECFAliquota: TSQLQuery;
    QVerificaCadMarcaCODIGO: TIntegerField;
    QVerificaCadMarcaNOME: TStringField;
    QVerificaCadGrupoCODIGO: TIntegerField;
    QVerificaCadGrupoNOME: TStringField;
    QVerificaCadECFAliquotaCODIGO: TIntegerField;
    QVerificaCadECFAliquotaNOME: TStringField;
    QVerificaCadECFAliquotaALIQUOTA: TFMTBCDField;
    QVerificaCadECFAliquotaCODIGOCUPOM: TStringField;
    QVerificaCadSecaoCODIGO: TIntegerField;
    QVerificaCadSecaoNOME: TStringField;
    SQLStoredProcCliExcluido: TSQLStoredProc;
    QConsultaRemoto: TSQLQuery;
    QConsultaLocal: TSQLQuery;
    SQLStoredProcProdExcluido: TSQLStoredProc;
    QVendaLocal: TSQLQuery;
    dsVendaLocal: TDataSource;
    QItemVendaLocal: TSQLQuery;
    QVendaLocalCODIGO: TIntegerField;
    QVendaLocalDATA: TDateField;
    QVendaLocalHORA: TTimeField;
    QVendaLocalNUMERO_ECF: TStringField;
    QVendaLocalNUMERO_CUPOM: TIntegerField;
    QVendaLocalCOD_CLIENTE: TIntegerField;
    QVendaLocalCOD_OPERADOR: TIntegerField;
    QVendaLocalCOD_VENDEDOR: TIntegerField;
    QVendaLocalSUBTOTAL: TFMTBCDField;
    QVendaLocalACRESCIMO: TFMTBCDField;
    QVendaLocalPERC_ACRESCIMO: TFMTBCDField;
    QVendaLocalDESCONTO: TFMTBCDField;
    QVendaLocalPERC_DESCONTO: TFMTBCDField;
    QVendaLocalTOTAL: TFMTBCDField;
    QVendaLocalDINHEIRO: TFMTBCDField;
    QVendaLocalCHEQUE: TFMTBCDField;
    QVendaLocalCHEQUE_PRE: TFMTBCDField;
    QVendaLocalCREDIARIO: TFMTBCDField;
    QVendaLocalCARTAO: TFMTBCDField;
    QVendaLocalTICKET: TFMTBCDField;
    QVendaLocalTROCO: TFMTBCDField;
    QVendaLocalTIPO: TStringField;
    QVendaLocalCUPOM_CANCELADO: TStringField;
    QVendaLocalNUMPGTO: TIntegerField;
    QVendaLocalPDV: TStringField;
    QVendaLocalBASE_ICMS: TFMTBCDField;
    QVendaLocalVALOR_ICMS: TFMTBCDField;
    QVendaLocalULT_ATUALIZACAO: TSQLTimeStampField;
    QItemVendaLocalCODIGO: TIntegerField;
    QItemVendaLocalNUMERO_ECF: TStringField;
    QItemVendaLocalNUMERO_CUPOM: TIntegerField;
    QItemVendaLocalITEM: TIntegerField;
    QItemVendaLocalCOD_PRODUTO: TIntegerField;
    QItemVendaLocalDESCRICAO: TStringField;
    QItemVendaLocalQUANTIDADE: TFMTBCDField;
    QItemVendaLocalUNIDADE: TStringField;
    QItemVendaLocalVL_UNITARIO: TFMTBCDField;
    QItemVendaLocalST: TStringField;
    QItemVendaLocalALIQUOTA: TFMTBCDField;
    QItemVendaLocalVL_TOTAL: TFMTBCDField;
    QItemVendaLocalTABELA: TStringField;
    QItemVendaLocalVL_UNIT_BRUTO: TFMTBCDField;
    QItemVendaLocalVL_TOTAL_BRUTO: TFMTBCDField;
    QItemVendaLocalPERC_DESCONTO: TFMTBCDField;
    QItemVendaLocalVALOR_DESCONTO: TFMTBCDField;
    QItemVendaLocalPERC_ACRESCIMO: TFMTBCDField;
    QItemVendaLocalVALOR_ACRESCIMO: TFMTBCDField;
    QItemVendaLocalBASE_ICMS: TFMTBCDField;
    QItemVendaLocalVALOR_ICMS: TFMTBCDField;
    QItemVendaLocalPERC_IPI: TFMTBCDField;
    QItemVendaLocalCST: TStringField;
    QVerifVendaPDV: TSQLQuery;
    TDeployULT_VERIF_VENDAS: TDateTimeField;
    QVendaRetag: TSQLQuery;
    dspVendaRetag: TDataSetProvider;
    TVendaRetag: TClientDataSet;
    dsVendaRetag: TDataSource;
    QItemVendaRetag: TSQLQuery;
    TItemVendaRetag: TClientDataSet;
    QVendaRetagCODVENDA: TIntegerField;
    QVendaRetagTIPO: TStringField;
    QVendaRetagCODCLIENTE: TIntegerField;
    QVendaRetagCODVENDEDOR1: TIntegerField;
    QVendaRetagCOMISSAO1: TFMTBCDField;
    QVendaRetagNUMPGTO: TIntegerField;
    QVendaRetagDATAEMISSAO: TDateField;
    QVendaRetagFINANCEIRO: TFMTBCDField;
    QVendaRetagPERCFINANCEIRO: TFMTBCDField;
    QVendaRetagDESCONTO: TFMTBCDField;
    QVendaRetagPERCDESCONTO: TFMTBCDField;
    QVendaRetagSUBTOTAL: TFMTBCDField;
    QVendaRetagTOTAL: TFMTBCDField;
    QVendaRetagTOTALCUSTO: TFMTBCDField;
    QVendaRetagSAIDA: TTimeField;
    QVendaRetagENTREGAFUTURA: TStringField;
    QVendaRetagENTREGACOMPLETA: TStringField;
    QVendaRetagSERVICO: TStringField;
    QVendaRetagCODPORTADOR: TIntegerField;
    QVendaRetagTROCO: TFMTBCDField;
    QVendaRetagDINHEIRO: TFMTBCDField;
    QVendaRetagCHEQUE: TFMTBCDField;
    QVendaRetagCARTAO: TFMTBCDField;
    QVendaRetagTICKET: TFMTBCDField;
    QVendaRetagCREDIARIO: TFMTBCDField;
    QVendaRetagCHEQUE_PRE: TFMTBCDField;
    QVendaRetagNUMERO_ECF: TStringField;
    QVendaRetagNUMERO_CUPOM: TIntegerField;
    QVendaRetagCOD_OPERADOR_PDV: TIntegerField;
    QVendaRetagPDV: TStringField;
    QVendaRetagCODIGO_VENDA_PDV: TIntegerField;
    QVendaRetagCANCELADO: TStringField;
    QVendaRetagBASE_ICMS: TFMTBCDField;
    QVendaRetagVALOR_ICMS: TFMTBCDField;
    TVendaRetagCODVENDA: TIntegerField;
    TVendaRetagTIPO: TStringField;
    TVendaRetagCODCLIENTE: TIntegerField;
    TVendaRetagCODVENDEDOR1: TIntegerField;
    TVendaRetagCOMISSAO1: TFMTBCDField;
    TVendaRetagNUMPGTO: TIntegerField;
    TVendaRetagDATAEMISSAO: TDateField;
    TVendaRetagFINANCEIRO: TFMTBCDField;
    TVendaRetagPERCFINANCEIRO: TFMTBCDField;
    TVendaRetagDESCONTO: TFMTBCDField;
    TVendaRetagPERCDESCONTO: TFMTBCDField;
    TVendaRetagSUBTOTAL: TFMTBCDField;
    TVendaRetagTOTAL: TFMTBCDField;
    TVendaRetagTOTALCUSTO: TFMTBCDField;
    TVendaRetagSAIDA: TTimeField;
    TVendaRetagENTREGAFUTURA: TStringField;
    TVendaRetagENTREGACOMPLETA: TStringField;
    TVendaRetagSERVICO: TStringField;
    TVendaRetagCODPORTADOR: TIntegerField;
    TVendaRetagTROCO: TFMTBCDField;
    TVendaRetagDINHEIRO: TFMTBCDField;
    TVendaRetagCHEQUE: TFMTBCDField;
    TVendaRetagCARTAO: TFMTBCDField;
    TVendaRetagTICKET: TFMTBCDField;
    TVendaRetagCREDIARIO: TFMTBCDField;
    TVendaRetagCHEQUE_PRE: TFMTBCDField;
    TVendaRetagNUMERO_ECF: TStringField;
    TVendaRetagNUMERO_CUPOM: TIntegerField;
    TVendaRetagCOD_OPERADOR_PDV: TIntegerField;
    TVendaRetagPDV: TStringField;
    TVendaRetagCODIGO_VENDA_PDV: TIntegerField;
    TVendaRetagCANCELADO: TStringField;
    TVendaRetagBASE_ICMS: TFMTBCDField;
    TVendaRetagVALOR_ICMS: TFMTBCDField;
    QItemVendaRetagCONTROLE: TIntegerField;
    QItemVendaRetagCODVENDA: TIntegerField;
    QItemVendaRetagCODPRODUTO: TIntegerField;
    QItemVendaRetagDATAEMISSAO: TDateField;
    QItemVendaRetagTIPO: TStringField;
    QItemVendaRetagCODCLIENTE: TIntegerField;
    QItemVendaRetagCODVENDEDOR1: TIntegerField;
    QItemVendaRetagCOMISSAO1: TFMTBCDField;
    QItemVendaRetagDESCRICAO: TStringField;
    QItemVendaRetagQTDE: TFMTBCDField;
    QItemVendaRetagQTDEPEGA: TFMTBCDField;
    QItemVendaRetagPRECOFIXO: TFMTBCDField;
    QItemVendaRetagVENDIDO: TFMTBCDField;
    QItemVendaRetagTOTALITEN: TFMTBCDField;
    QItemVendaRetagTABELA: TStringField;
    QItemVendaRetagCODGRUPO: TIntegerField;
    QItemVendaRetagCODMARCA: TIntegerField;
    QItemVendaRetagMAODEOBRA: TStringField;
    QItemVendaRetagCUSTOFINAL: TFMTBCDField;
    QItemVendaRetagTOTALCUSTO: TFMTBCDField;
    QItemVendaRetagCODPORTADOR: TIntegerField;
    QItemVendaRetagSERVICO: TStringField;
    QItemVendaRetagCOMNOTA: TStringField;
    QItemVendaRetagNUMERO_ECF: TStringField;
    QItemVendaRetagNUMERO_CUPOM: TIntegerField;
    QItemVendaRetagITEM: TIntegerField;
    QItemVendaRetagST: TStringField;
    QItemVendaRetagALIQUOTA: TFMTBCDField;
    QItemVendaRetagCANCELADO: TStringField;
    QItemVendaRetagBASE_ICMS: TFMTBCDField;
    QItemVendaRetagVALOR_ICMS: TFMTBCDField;
    QItemVendaRetagIPI: TFMTBCDField;
    QItemVendaRetagVALOR_UNIT_BRUTO: TFMTBCDField;
    QItemVendaRetagVALOR_TOTAL_BRUTO: TFMTBCDField;
    QItemVendaRetagPERC_DESCONTO: TFMTBCDField;
    QItemVendaRetagVALOR_DESCONTO: TFMTBCDField;
    QItemVendaRetagPERC_ACRESCIMO: TFMTBCDField;
    QItemVendaRetagVALOR_ACRESCIMO: TFMTBCDField;
    QItemVendaRetagCST: TStringField;
    TVendaRetagQItemVendaRetag: TDataSetField;
    TItemVendaRetagCONTROLE: TIntegerField;
    TItemVendaRetagCODVENDA: TIntegerField;
    TItemVendaRetagCODPRODUTO: TIntegerField;
    TItemVendaRetagDATAEMISSAO: TDateField;
    TItemVendaRetagTIPO: TStringField;
    TItemVendaRetagCODCLIENTE: TIntegerField;
    TItemVendaRetagCODVENDEDOR1: TIntegerField;
    TItemVendaRetagCOMISSAO1: TFMTBCDField;
    TItemVendaRetagDESCRICAO: TStringField;
    TItemVendaRetagQTDE: TFMTBCDField;
    TItemVendaRetagQTDEPEGA: TFMTBCDField;
    TItemVendaRetagPRECOFIXO: TFMTBCDField;
    TItemVendaRetagVENDIDO: TFMTBCDField;
    TItemVendaRetagTOTALITEN: TFMTBCDField;
    TItemVendaRetagTABELA: TStringField;
    TItemVendaRetagCODGRUPO: TIntegerField;
    TItemVendaRetagCODMARCA: TIntegerField;
    TItemVendaRetagMAODEOBRA: TStringField;
    TItemVendaRetagCUSTOFINAL: TFMTBCDField;
    TItemVendaRetagTOTALCUSTO: TFMTBCDField;
    TItemVendaRetagCODPORTADOR: TIntegerField;
    TItemVendaRetagSERVICO: TStringField;
    TItemVendaRetagCOMNOTA: TStringField;
    TItemVendaRetagNUMERO_ECF: TStringField;
    TItemVendaRetagNUMERO_CUPOM: TIntegerField;
    TItemVendaRetagITEM: TIntegerField;
    TItemVendaRetagST: TStringField;
    TItemVendaRetagALIQUOTA: TFMTBCDField;
    TItemVendaRetagCANCELADO: TStringField;
    TItemVendaRetagBASE_ICMS: TFMTBCDField;
    TItemVendaRetagVALOR_ICMS: TFMTBCDField;
    TItemVendaRetagIPI: TFMTBCDField;
    TItemVendaRetagVALOR_UNIT_BRUTO: TFMTBCDField;
    TItemVendaRetagVALOR_TOTAL_BRUTO: TFMTBCDField;
    TItemVendaRetagPERC_DESCONTO: TFMTBCDField;
    TItemVendaRetagVALOR_DESCONTO: TFMTBCDField;
    TItemVendaRetagPERC_ACRESCIMO: TFMTBCDField;
    TItemVendaRetagVALOR_ACRESCIMO: TFMTBCDField;
    TItemVendaRetagCST: TStringField;
    QGenRetag: TSQLQuery;
    QItemVendaRetagCODGRUPO_1: TIntegerField;
    QItemVendaRetagCODMARCA_1: TIntegerField;
    QItemVendaRetagCUSTOFINAL_1: TFMTBCDField;
    TItemVendaRetagCODGRUPO_1: TIntegerField;
    TItemVendaRetagCODMARCA_1: TIntegerField;
    TItemVendaRetagCUSTOFINAL_1: TFMTBCDField;
    dspVendaLocal: TDataSetProvider;
    TVendaLocal: TClientDataSet;
    TVendaLocalCODIGO: TIntegerField;
    TVendaLocalDATA: TDateField;
    TVendaLocalHORA: TTimeField;
    TVendaLocalNUMERO_ECF: TStringField;
    TVendaLocalNUMERO_CUPOM: TIntegerField;
    TVendaLocalCOD_CLIENTE: TIntegerField;
    TVendaLocalCOD_OPERADOR: TIntegerField;
    TVendaLocalCOD_VENDEDOR: TIntegerField;
    TVendaLocalSUBTOTAL: TFMTBCDField;
    TVendaLocalACRESCIMO: TFMTBCDField;
    TVendaLocalPERC_ACRESCIMO: TFMTBCDField;
    TVendaLocalDESCONTO: TFMTBCDField;
    TVendaLocalPERC_DESCONTO: TFMTBCDField;
    TVendaLocalTOTAL: TFMTBCDField;
    TVendaLocalDINHEIRO: TFMTBCDField;
    TVendaLocalCHEQUE: TFMTBCDField;
    TVendaLocalCHEQUE_PRE: TFMTBCDField;
    TVendaLocalCREDIARIO: TFMTBCDField;
    TVendaLocalCARTAO: TFMTBCDField;
    TVendaLocalTICKET: TFMTBCDField;
    TVendaLocalTROCO: TFMTBCDField;
    TVendaLocalTIPO: TStringField;
    TVendaLocalCUPOM_CANCELADO: TStringField;
    TVendaLocalNUMPGTO: TIntegerField;
    TVendaLocalPDV: TStringField;
    TVendaLocalBASE_ICMS: TFMTBCDField;
    TVendaLocalVALOR_ICMS: TFMTBCDField;
    TVendaLocalULT_ATUALIZACAO: TSQLTimeStampField;
    TVendaLocalQItemVendaLocal: TDataSetField;
    TItemVendaLocal: TClientDataSet;
    TItemVendaLocalCODIGO: TIntegerField;
    TItemVendaLocalNUMERO_ECF: TStringField;
    TItemVendaLocalNUMERO_CUPOM: TIntegerField;
    TItemVendaLocalITEM: TIntegerField;
    TItemVendaLocalCOD_PRODUTO: TIntegerField;
    TItemVendaLocalDESCRICAO: TStringField;
    TItemVendaLocalQUANTIDADE: TFMTBCDField;
    TItemVendaLocalUNIDADE: TStringField;
    TItemVendaLocalVL_UNITARIO: TFMTBCDField;
    TItemVendaLocalST: TStringField;
    TItemVendaLocalALIQUOTA: TFMTBCDField;
    TItemVendaLocalVL_TOTAL: TFMTBCDField;
    TItemVendaLocalTABELA: TStringField;
    TItemVendaLocalVL_UNIT_BRUTO: TFMTBCDField;
    TItemVendaLocalVL_TOTAL_BRUTO: TFMTBCDField;
    TItemVendaLocalPERC_DESCONTO: TFMTBCDField;
    TItemVendaLocalVALOR_DESCONTO: TFMTBCDField;
    TItemVendaLocalPERC_ACRESCIMO: TFMTBCDField;
    TItemVendaLocalVALOR_ACRESCIMO: TFMTBCDField;
    TItemVendaLocalBASE_ICMS: TFMTBCDField;
    TItemVendaLocalVALOR_ICMS: TFMTBCDField;
    TItemVendaLocalPERC_IPI: TFMTBCDField;
    TItemVendaLocalCST: TStringField;
    QReducoesLocal: TSQLQuery;
    QVerifReducaoRetag: TSQLQuery;
    QReducoesLocalCODIGO: TIntegerField;
    QReducoesLocalDATA_HORA: TSQLTimeStampField;
    QReducoesLocalNRO_SERIE_EQP: TStringField;
    QReducoesLocalNR_ORDEM_EQP: TStringField;
    QReducoesLocalMODELO_DOC: TStringField;
    QReducoesLocalNRO_CONTADOR_INICIO: TIntegerField;
    QReducoesLocalNRO_CONTADOR_FIM: TIntegerField;
    QReducoesLocalNR_CONTADOR_Z: TIntegerField;
    QReducoesLocalCONTADOR_REINICIO: TIntegerField;
    QReducoesLocalVALOR_VENDA_BRUTA: TFMTBCDField;
    QReducoesLocalVALOR_VENDA_GERAL: TFMTBCDField;
    QReducoesLocalVALOR_CANCELAMENTOS: TFMTBCDField;
    QReducoesLocalVALOR_DESCONTOS: TFMTBCDField;
    QReducoesLocalVALOR_ISSQN: TFMTBCDField;
    QReducoesLocalVALOR_SUBST_TRIB: TFMTBCDField;
    QReducoesLocalVALOR_ISENTO: TFMTBCDField;
    QReducoesLocalVALOR_NAO_INCIDENCIA: TFMTBCDField;
    QReducoesLocalALIQUOTA01: TStringField;
    QReducoesLocalVALOR_TPARCIAL01: TFMTBCDField;
    QReducoesLocalALIQUOTA02: TStringField;
    QReducoesLocalVALOR_TPARCIAL02: TFMTBCDField;
    QReducoesLocalALIQUOTA03: TStringField;
    QReducoesLocalVALOR_TPARCIAL03: TFMTBCDField;
    QReducoesLocalALIQUOTA04: TStringField;
    QReducoesLocalVALOR_TPARCIAL04: TFMTBCDField;
    QReducoesLocalALIQUOTA05: TStringField;
    QReducoesLocalVALOR_TPARCIAL05: TFMTBCDField;
    QReducoesLocalALIQUOTA06: TStringField;
    QReducoesLocalVALOR_TPARCIAL06: TFMTBCDField;
    QReducoesLocalALIQUOTA07: TStringField;
    QReducoesLocalVALOR_TPARCIAL07: TFMTBCDField;
    QReducoesLocalALIQUOTA08: TStringField;
    QReducoesLocalVALOR_TPARCIAL08: TFMTBCDField;
    QReducoesLocalALIQUOTA09: TStringField;
    QReducoesLocalVALOR_TPARCIAL09: TFMTBCDField;
    QReducoesLocalALIQUOTA010: TStringField;
    QReducoesLocalVALOR_TPARCIAL010: TFMTBCDField;
    QReducoesLocalDATA_MOVIMENTO: TDateField;
    QCadReducaoRetag: TSQLQuery;
    dspCadReducaoRetag: TDataSetProvider;
    QCadReducaoRetagCODIGO: TIntegerField;
    QCadReducaoRetagDATA_HORA: TSQLTimeStampField;
    QCadReducaoRetagDATA_MOVIMENTO: TDateField;
    QCadReducaoRetagNRO_SERIE_EQP: TStringField;
    QCadReducaoRetagNR_ORDEM_EQP: TStringField;
    QCadReducaoRetagMODELO_DOC: TStringField;
    QCadReducaoRetagNRO_CONTADOR_INICIO: TIntegerField;
    QCadReducaoRetagNRO_CONTADOR_FIM: TIntegerField;
    QCadReducaoRetagNR_CONTADOR_Z: TIntegerField;
    QCadReducaoRetagCONTADOR_REINICIO: TIntegerField;
    QCadReducaoRetagVALOR_VENDA_BRUTA: TFMTBCDField;
    QCadReducaoRetagVALOR_VENDA_GERAL: TFMTBCDField;
    QCadReducaoRetagVALOR_CANCELAMENTOS: TFMTBCDField;
    QCadReducaoRetagVALOR_DESCONTOS: TFMTBCDField;
    QCadReducaoRetagVALOR_ISSQN: TFMTBCDField;
    QCadReducaoRetagVALOR_SUBST_TRIB: TFMTBCDField;
    QCadReducaoRetagVALOR_ISENTO: TFMTBCDField;
    QCadReducaoRetagVALOR_NAO_INCIDENCIA: TFMTBCDField;
    QCadReducaoRetagALIQUOTA01: TStringField;
    QCadReducaoRetagVALOR_TPARCIAL01: TFMTBCDField;
    QCadReducaoRetagALIQUOTA02: TStringField;
    QCadReducaoRetagVALOR_TPARCIAL02: TFMTBCDField;
    QCadReducaoRetagALIQUOTA03: TStringField;
    QCadReducaoRetagVALOR_TPARCIAL03: TFMTBCDField;
    QCadReducaoRetagALIQUOTA04: TStringField;
    QCadReducaoRetagVALOR_TPARCIAL04: TFMTBCDField;
    QCadReducaoRetagALIQUOTA05: TStringField;
    QCadReducaoRetagVALOR_TPARCIAL05: TFMTBCDField;
    QCadReducaoRetagALIQUOTA06: TStringField;
    QCadReducaoRetagVALOR_TPARCIAL06: TFMTBCDField;
    QCadReducaoRetagALIQUOTA07: TStringField;
    QCadReducaoRetagVALOR_TPARCIAL07: TFMTBCDField;
    QCadReducaoRetagALIQUOTA08: TStringField;
    QCadReducaoRetagVALOR_TPARCIAL08: TFMTBCDField;
    QCadReducaoRetagALIQUOTA09: TStringField;
    QCadReducaoRetagVALOR_TPARCIAL09: TFMTBCDField;
    QCadReducaoRetagALIQUOTA010: TStringField;
    QCadReducaoRetagVALOR_TPARCIAL010: TFMTBCDField;
    QCadReducaoRetagCOD_REDUCAO_PDV: TIntegerField;
    TCadReducaoRetag: TClientDataSet;
    TCadReducaoRetagCODIGO: TIntegerField;
    TCadReducaoRetagDATA_HORA: TSQLTimeStampField;
    TCadReducaoRetagDATA_MOVIMENTO: TDateField;
    TCadReducaoRetagNRO_SERIE_EQP: TStringField;
    TCadReducaoRetagNR_ORDEM_EQP: TStringField;
    TCadReducaoRetagMODELO_DOC: TStringField;
    TCadReducaoRetagNRO_CONTADOR_INICIO: TIntegerField;
    TCadReducaoRetagNRO_CONTADOR_FIM: TIntegerField;
    TCadReducaoRetagNR_CONTADOR_Z: TIntegerField;
    TCadReducaoRetagCONTADOR_REINICIO: TIntegerField;
    TCadReducaoRetagVALOR_VENDA_BRUTA: TFMTBCDField;
    TCadReducaoRetagVALOR_VENDA_GERAL: TFMTBCDField;
    TCadReducaoRetagVALOR_CANCELAMENTOS: TFMTBCDField;
    TCadReducaoRetagVALOR_DESCONTOS: TFMTBCDField;
    TCadReducaoRetagVALOR_ISSQN: TFMTBCDField;
    TCadReducaoRetagVALOR_SUBST_TRIB: TFMTBCDField;
    TCadReducaoRetagVALOR_ISENTO: TFMTBCDField;
    TCadReducaoRetagVALOR_NAO_INCIDENCIA: TFMTBCDField;
    TCadReducaoRetagALIQUOTA01: TStringField;
    TCadReducaoRetagVALOR_TPARCIAL01: TFMTBCDField;
    TCadReducaoRetagALIQUOTA02: TStringField;
    TCadReducaoRetagVALOR_TPARCIAL02: TFMTBCDField;
    TCadReducaoRetagALIQUOTA03: TStringField;
    TCadReducaoRetagVALOR_TPARCIAL03: TFMTBCDField;
    TCadReducaoRetagALIQUOTA04: TStringField;
    TCadReducaoRetagVALOR_TPARCIAL04: TFMTBCDField;
    TCadReducaoRetagALIQUOTA05: TStringField;
    TCadReducaoRetagVALOR_TPARCIAL05: TFMTBCDField;
    TCadReducaoRetagALIQUOTA06: TStringField;
    TCadReducaoRetagVALOR_TPARCIAL06: TFMTBCDField;
    TCadReducaoRetagALIQUOTA07: TStringField;
    TCadReducaoRetagVALOR_TPARCIAL07: TFMTBCDField;
    TCadReducaoRetagALIQUOTA08: TStringField;
    TCadReducaoRetagVALOR_TPARCIAL08: TFMTBCDField;
    TCadReducaoRetagALIQUOTA09: TStringField;
    TCadReducaoRetagVALOR_TPARCIAL09: TFMTBCDField;
    TCadReducaoRetagALIQUOTA010: TStringField;
    TCadReducaoRetagVALOR_TPARCIAL010: TFMTBCDField;
    TCadReducaoRetagCOD_REDUCAO_PDV: TIntegerField;
    QVendaLocalCOD_DAV: TIntegerField;
    TVendaLocalCOD_DAV: TIntegerField;
    QVendaLocalNUM_CCF_CUPOM: TIntegerField;
    TVendaLocalNUM_CCF_CUPOM: TIntegerField;
    QVendaRetagNUM_CCF_CUPOM: TIntegerField;
    TVendaRetagNUM_CCF_CUPOM: TIntegerField;
    QReducoesLocalPOSI_ALIQUOTA01: TStringField;
    QReducoesLocalPOSI_ALIQUOTA02: TStringField;
    QReducoesLocalPOSI_ALIQUOTA03: TStringField;
    QReducoesLocalPOSI_ALIQUOTA04: TStringField;
    QReducoesLocalPOSI_ALIQUOTA05: TStringField;
    QReducoesLocalPOSI_ALIQUOTA06: TStringField;
    QReducoesLocalPOSI_ALIQUOTA07: TStringField;
    QReducoesLocalPOSI_ALIQUOTA08: TStringField;
    QReducoesLocalPOSI_ALIQUOTA09: TStringField;
    QReducoesLocalPOSI_ALIQUOTA010: TStringField;
    QCadReducaoRetagPOSI_ALIQUOTA01: TStringField;
    QCadReducaoRetagPOSI_ALIQUOTA02: TStringField;
    QCadReducaoRetagPOSI_ALIQUOTA03: TStringField;
    QCadReducaoRetagPOSI_ALIQUOTA04: TStringField;
    QCadReducaoRetagPOSI_ALIQUOTA05: TStringField;
    QCadReducaoRetagPOSI_ALIQUOTA06: TStringField;
    QCadReducaoRetagPOSI_ALIQUOTA07: TStringField;
    QCadReducaoRetagPOSI_ALIQUOTA08: TStringField;
    QCadReducaoRetagPOSI_ALIQUOTA09: TStringField;
    QCadReducaoRetagPOSI_ALIQUOTA010: TStringField;
    TCadReducaoRetagPOSI_ALIQUOTA01: TStringField;
    TCadReducaoRetagPOSI_ALIQUOTA02: TStringField;
    TCadReducaoRetagPOSI_ALIQUOTA03: TStringField;
    TCadReducaoRetagPOSI_ALIQUOTA04: TStringField;
    TCadReducaoRetagPOSI_ALIQUOTA05: TStringField;
    TCadReducaoRetagPOSI_ALIQUOTA06: TStringField;
    TCadReducaoRetagPOSI_ALIQUOTA07: TStringField;
    TCadReducaoRetagPOSI_ALIQUOTA08: TStringField;
    TCadReducaoRetagPOSI_ALIQUOTA09: TStringField;
    TCadReducaoRetagPOSI_ALIQUOTA010: TStringField;
    QVerificaCadEstoqueCOD_SIT: TStringField;
    QVerificaCadEstoqueDATAULTVENDA: TDateField;
    QVerificaCadEstoqueIAT: TStringField;
    QVerificaCadEstoqueIPPT: TStringField;
    SQLStoredProcEstoqueGrade: TSQLStoredProc;
    QVerificaCadEstoqueGrade: TSQLQuery;
    QVerificaCadEstoqueGradeCODIGO: TIntegerField;
    QVerificaCadEstoqueGradeCOD_PRODUTO: TIntegerField;
    QVerificaCadEstoqueGradeVARIACAO: TStringField;
    QVerificaCadEstoqueGradeQTDE: TFMTBCDField;
    QVerificaCadEstoqueGradeQTDE_EF: TFMTBCDField;
    QVerificaCadEstoqueGradeQTDE_MINIMA: TFMTBCDField;
    QVerificaCadEstoqueGradeCOD_BARRA: TStringField;
    QVerificaCadEstoqueGradeREFERENCIA: TStringField;
    QVerificaCadEstoqueGradeMED: TStringField;
    QVerificaCadEstoqueGradeCOD_COR: TSmallintField;
    QVerificaCadEstoqueGradeCOD_TAMANHO: TSmallintField;
    QVerifCadCores: TSQLQuery;
    QVerifCadCoresCODIGO: TIntegerField;
    QVerifCadCoresNOME_COR: TStringField;
    QVerifCadTamanho: TSQLQuery;
    QVerifCadTamanhoCODIGO: TIntegerField;
    QVerifCadTamanhoNOME_TAMANHO: TStringField;
    SQLStoredProcCores: TSQLStoredProc;
    SQLStoredProcTamanho: TSQLStoredProc;
    QVendaGradeLocal: TSQLQuery;
    dspVendaGradeLocal: TDataSetProvider;
    TVendaGradeLocal: TClientDataSet;
    QVendaGradeLocalCODIGO: TIntegerField;
    QVendaGradeLocalCOD_VENDA: TIntegerField;
    QVendaGradeLocalCOD_PRODUTO: TIntegerField;
    QVendaGradeLocalCOD_GRADE: TIntegerField;
    QVendaGradeLocalQTDE: TFMTBCDField;
    QVendaGradeLocalCOD_COR: TSmallintField;
    QVendaGradeLocalCOD_TAMANHO: TSmallintField;
    TVendaGradeLocalCODIGO: TIntegerField;
    TVendaGradeLocalCOD_VENDA: TIntegerField;
    TVendaGradeLocalCOD_PRODUTO: TIntegerField;
    TVendaGradeLocalCOD_GRADE: TIntegerField;
    TVendaGradeLocalQTDE: TFMTBCDField;
    TVendaGradeLocalCOD_COR: TSmallintField;
    TVendaGradeLocalCOD_TAMANHO: TSmallintField;
    QVendaGradeRetag: TSQLQuery;
    dspVendaGradeRetag: TDataSetProvider;
    TVendaGradeRetag: TClientDataSet;
    QVendaGradeRetagCODIGO: TIntegerField;
    QVendaGradeRetagCOD_VENDA: TIntegerField;
    QVendaGradeRetagCOD_PRODUTO: TIntegerField;
    QVendaGradeRetagCOD_GRADE: TIntegerField;
    QVendaGradeRetagQTDE: TFMTBCDField;
    QVendaGradeRetagCOD_COR: TSmallintField;
    QVendaGradeRetagCOD_TAMANHO: TSmallintField;
    TVendaGradeRetagCODIGO: TIntegerField;
    TVendaGradeRetagCOD_VENDA: TIntegerField;
    TVendaGradeRetagCOD_PRODUTO: TIntegerField;
    TVendaGradeRetagCOD_GRADE: TIntegerField;
    TVendaGradeRetagQTDE: TFMTBCDField;
    TVendaGradeRetagCOD_COR: TSmallintField;
    TVendaGradeRetagCOD_TAMANHO: TSmallintField;
    QVendaRetagMODELO_NF: TStringField;
    QVendaRetagSERIE_NF: TStringField;
    TVendaRetagMODELO_NF: TStringField;
    TVendaRetagSERIE_NF: TStringField;
    QVerificaCadEmpresaCONTATO: TStringField;
    procedure TCPTestaConexaoConnected(Sender: TObject);
    procedure TDeployAfterDelete(DataSet: TDataSet);
    procedure TDeployAfterPost(DataSet: TDataSet);
    procedure dspVendaRetagBeforeUpdateRecord(Sender: TObject;
      SourceDS: TDataSet; DeltaDS: TCustomClientDataSet;
      UpdateKind: TUpdateKind; var Applied: Boolean);
    procedure TVendaRetagNewRecord(DataSet: TDataSet);
    procedure dspCadReducaoRetagBeforeUpdateRecord(Sender: TObject;
      SourceDS: TDataSet; DeltaDS: TCustomClientDataSet;
      UpdateKind: TUpdateKind; var Applied: Boolean);
    procedure TCadReducaoRetagNewRecord(DataSet: TDataSet);
    procedure dspVendaGradeRetagBeforeUpdateRecord(Sender: TObject;
      SourceDS: TDataSet; DeltaDS: TCustomClientDataSet;
      UpdateKind: TUpdateKind; var Applied: Boolean);
    procedure TVendaGradeRetagNewRecord(DataSet: TDataSet);
  private
    { Private declarations }
    FSeqTmp, FNumCodigo : Integer;
  public
    { Public declarations }
  end;

var
  DM: TDM;

implementation

uses UMonitorPDV;

{$R *.dfm}

procedure TDM.TCPTestaConexaoConnected(Sender: TObject);
begin
     With FMonitorPDV
     do AbreConexaoRemota;
end;

procedure TDM.TDeployAfterDelete(DataSet: TDataSet);
begin
    TDeploy.SaveToFile(TDeploy.FileName,dfXML);
end;

procedure TDM.TDeployAfterPost(DataSet: TDataSet);
begin
    TDeploy.SaveToFile(TDeploy.FileName,dfXML);
end;

procedure TDM.dspVendaRetagBeforeUpdateRecord(Sender: TObject;
  SourceDS: TDataSet; DeltaDS: TCustomClientDataSet;
  UpdateKind: TUpdateKind; var Applied: Boolean);
begin
    if UpdateKind = ukInsert
    then begin
          if SourceDs = QVendaRetag
          then begin
                With QGenRetag
                do begin
                   Close;
                   Sql.Clear;
                   Sql.Add('SELECT GEN_ID(GEN_VENDA_ID,1) AS CODIGO_NOVO FROM DUAL');
                   Open;
                   end;
                try
                  FNumCodigo := QGenRetag.FieldByName('CODIGO_NOVO').AsInteger;
                finally
                  QGenRetag.Close;
                end;
                DeltaDs.FieldByName('CODVENDA').NewValue := FNumCodigo;
          end else if (SourceDs = QItemVendaRetag)
          then if TItemVendaRetag.FieldByName('CODVENDA').AsInteger < 0
          then DeltaDs.FieldByName('CODVENDA').NewValue := FNumCodigo;
      end;
end;

procedure TDM.TVendaRetagNewRecord(DataSet: TDataSet);
begin
     Dec(FSeqTmp);
     TVendaRetag.FieldByName('CODVENDA').AsInteger:=FSeqTmp;
end;

procedure TDM.dspCadReducaoRetagBeforeUpdateRecord(Sender: TObject;
  SourceDS: TDataSet; DeltaDS: TCustomClientDataSet;
  UpdateKind: TUpdateKind; var Applied: Boolean);
begin
     if UpdateKind = ukInsert
     then begin
          With QGenRetag
          do begin
             Close;
             Sql.Clear;
             Sql.Add('SELECT GEN_ID(GEN_REDUCOES_ID,1) AS CODIGO_NOVO FROM DUAL');
             Open;
             end;
          Try
             FNumCodigo := QGenRetag.FieldByName('CODIGO_NOVO').AsInteger;
          Finally
             QGenRetag.Close;
             end;
          DeltaDs.FieldByName('CODIGO').NewValue:=FNumCodigo;
       end;
end;

procedure TDM.TCadReducaoRetagNewRecord(DataSet: TDataSet);
begin
     Dec(FSeqTmp);
     TCadReducaoRetag.FieldByName('CODIGO').AsInteger:=FSeqTmp;
end;

procedure TDM.dspVendaGradeRetagBeforeUpdateRecord(Sender: TObject;
  SourceDS: TDataSet; DeltaDS: TCustomClientDataSet;
  UpdateKind: TUpdateKind; var Applied: Boolean);
begin
     if UpdateKind = ukInsert
     then begin
          With QGenRetag
          do begin
             Close;
             Sql.Clear;
             Sql.Add('SELECT GEN_ID(GEN_VENDA_GRADE_ID,1) AS CODIGO_NOVO FROM DUAL');
             Open;
             end;
          Try
             FNumCodigo := QGenRetag.FieldByName('CODIGO_NOVO').AsInteger;
          Finally
             QGenRetag.Close;
             end;
          DeltaDs.FieldByName('CODIGO').NewValue:=FNumCodigo;
       end;
end;

procedure TDM.TVendaGradeRetagNewRecord(DataSet: TDataSet);
begin
     Dec(FSeqTmp);
     TVendaGradeRetag.FieldByName('CODIGO').AsInteger:=FSeqTmp;
end;

end.
